import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';
import { homedir } from 'os';
import { resolve } from 'path';
import fs from 'fs';
import os from 'os';

export default defineConfig({
    server: detectServerConfig(),
    plugins: [
        laravel({
            input: 'resources/js/app.js',
            refresh: true
        }),
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
        }),
    ],
    resolve: {
        alias: {
            "@": "/resources/js"
        }
    }
})

function detectServerConfig() {
    let host = 'unreal.test';

    let keyPath = '';
    let certificatePath = '';
    if(os.platform() === "linux") {
        // This is just my setup for working under WSL2 (Ubuntu) with self-signed certs generated by easyrsa.
        keyPath = resolve(homedir(), `easyrsa/pki/private/Unreal.key`)
        certificatePath = resolve(homedir(), `easyrsa/pki/issued/Unreal.crt`)
    } else if(os.platform() === "darwin") {
        // MacOS using Laravel Valet.
        keyPath = resolve(homedir(), `.config/valet/Certificates/${host}.key`)
        certificatePath = resolve(homedir(), `.config/valet/Certificates/${host}.crt`)
    }

    if (!fs.existsSync(keyPath) || !fs.existsSync(certificatePath)) {
        return {};
    }

    return {
        host,
        https: {
            key: fs.readFileSync(keyPath),
            cert: fs.readFileSync(certificatePath)
        }
    }
}
